version: "3.0"
services:
  postgres:
    image: postgres:14.0
    container_name: postgres_container
    environment:
      environment:
      POSTGRES_DB: "mts"
      POSTGRES_USER: "server"
      POSTGRES_PASSWORD: "qtzxc1"
    ports:
      - "50000:5432"
      

  pgadmin:
    image: dpage/pgadmin4:latest 
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: "server@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "passwd"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    restart: unless-stopped
    ports:
      - "5050:80" 
    depends_on:
      - postgres 





